import json
import os


# ============================================================
# TEMPLATE SERVICE
#
# Loads creative template categories, templates and model
# profiles from JSON configuration files.
#
# Templates are DATA. Adding a third template only requires
# dropping a new JSON file into config/templates/<category>/.
# ============================================================

BASE_DIR = os.path.dirname(
    os.path.abspath(__file__)
)

CONFIG_DIR = os.path.join(
    os.path.dirname(BASE_DIR),
    "config"
)

CATEGORIES_DIR = os.path.join(
    CONFIG_DIR,
    "categories"
)

TEMPLATES_DIR = os.path.join(
    CONFIG_DIR,
    "templates"
)

MODEL_PROFILES_DIR = os.path.join(
    CONFIG_DIR,
    "model-profiles"
)

# ------------------------------------------------------------
# Downloaded prompt library
# (generated by product_prompt_library_downloader)
# ------------------------------------------------------------

PROMPT_LIBRARY_PATH = os.path.join(
    os.path.dirname(BASE_DIR),
    "product-prompt-library",
    "templates.json"
)

DEFAULT_LIBRARY_MODEL_PROFILE = "qwen_product_quality"



REQUIRED_TEMPLATE_FIELDS = [
    "id",
    "categoryId",
    "name",
    "promptTemplate",
    "modelProfileId",
    "enabled"
]


def _load_json_files(directory):
    """Load every .json file in a directory as a list of dicts."""

    items = []

    if not os.path.isdir(directory):
        return items

    for filename in sorted(os.listdir(directory)):

        if not filename.endswith(".json"):
            continue

        path = os.path.join(
            directory,
            filename
        )

        try:

            with open(path, "r", encoding="utf-8") as f:
                items.append(json.load(f))

        except (OSError, ValueError) as e:

            print(
                f"Template service: failed to load "
                f"{path}: {e}",
                flush=True
            )

    return items


def _validate_template(template):

    for field in REQUIRED_TEMPLATE_FIELDS:

        if field not in template:
            raise ValueError(
                f"Template '{template.get('id', '?')}' "
                f"is missing required field '{field}'."
            )

    if not template["promptTemplate"]:
        raise ValueError(
            f"Template '{template['id']}' has an "
            f"empty promptTemplate."
        )


# ------------------------------------------------------------
# CATEGORIES
# ------------------------------------------------------------

def get_categories():

    """Return all enabled categories."""

    categories = _load_json_files(CATEGORIES_DIR)

    return [c for c in categories if c.get("enabled")]


def get_category(category_id):

    for category in get_categories():

        if category["id"] == category_id:
            return category

    return None


# ------------------------------------------------------------
# TEMPLATES
# ------------------------------------------------------------

def get_templates(category_id=None):

    """
    Return enabled templates,
    optionally filtered by category id.
    Invalid template files are skipped with a warning.
    """

    templates = []

    # Walk category subdirectories
    # (templates/product_ads/*.json etc.)
    if not os.path.isdir(TEMPLATES_DIR):
        return templates

    for sub in sorted(os.listdir(TEMPLATES_DIR)):

        sub_dir = os.path.join(TEMPLATES_DIR, sub)

        if not os.path.isdir(sub_dir):
            continue

        for raw in _load_json_files(sub_dir):

            try:

                _validate_template(raw)

            except ValueError as e:

                print(str(e), flush=True)
                continue

            if not raw.get("enabled"):
                continue

            if (
                category_id
                and raw["categoryId"] != category_id
            ):
                continue

            # Existing curated product-ad templates are product-photography
            # templates, so keep them in the Product & Brand category.
            if raw.get("categoryId") == "product_ads":
                raw.setdefault("subcategoryId", "product_brand")

            templates.append(raw)

    # --------------------------------------------------------
    # Downloaded prompt library entries
    # --------------------------------------------------------

    for item in get_prompt_library():

        if (
            category_id
            and item["categoryId"] != category_id
        ):
            continue

        templates.append(item)

    return templates


def get_template(template_id):

    for template in get_templates():

        if template["id"] == template_id:
            return template

    return None


# ------------------------------------------------------------
# MODEL PROFILES
# ------------------------------------------------------------

def get_model_profile(profile_id):

    for profile in _load_json_files(MODEL_PROFILES_DIR):

        if profile.get("id") == profile_id:
            return profile

    return None


# ------------------------------------------------------------
# PROMPT LIBRARY
#
# Loads the downloaded open-source prompt collection
# (product-prompt-library/templates.json) and converts each
# entry into the internal template shape so it can be used
# exactly like a curated template in the generation flow.
#
# Refresh the library any time by re-running:
#   python product_prompt_library_downloader/download_library.py
# ------------------------------------------------------------

_SUBCATEGORY_LABELS = {
    "product_brand": "Product & Brand Photography",
    "food_drink": "Food & Drink",
    "poster_campaign": "Poster & Campaign"
}


def _convert_library_record(record):

    prompt = (record.get("prompt") or "").strip()

    if not prompt:
        return None

    subcategory = record.get("subcategory", "")

    return {
        "id": f"lib_{record.get('id')}",
        "categoryId": record.get("category", "product_ads"),
        "subcategoryId": record.get("subcategory") or None,
        "name": (record.get("name") or record.get("id", ""))[:120],
        "description": _SUBCATEGORY_LABELS.get(
            subcategory,
            subcategory.replace("_", " ").title()
        ),
        "thumbnail": record.get("image"),  # Library prompt image
        "promptTemplate": prompt,
        "variables": {},
        "modelProfileId": DEFAULT_LIBRARY_MODEL_PROFILE,
        "enabled": True,
        "origin": "library",
        "source": record.get("source")
    }


def get_prompt_library():

    """Return all prompt-library entries as internal templates."""

    if not os.path.isfile(PROMPT_LIBRARY_PATH):
        return []

    try:

        with open(PROMPT_LIBRARY_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)

    except (OSError, ValueError) as e:

        print(
            f"Prompt library: failed to load "
            f"{PROMPT_LIBRARY_PATH}: {e}",
            flush=True
        )

        return []

    converted = []

    for record in data.get("templates", []):

        item = _convert_library_record(record)

        if item:
            converted.append(item)

    return converted

